"""empty message

Revision ID: 1ff648b1d8a3
Revises: be1370778c68
Create Date: 2017-02-24 11:04:12.732906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff648b1d8a3'
down_revision = 'be1370778c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chatroom', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatroom', type_='unique')
    # ### end Alembic commands ###
